### ISSUE TITLE
How can I add Footer to every page

### ISSUE THREAD

**Issue by meysamhadigheh** [tejpratap46/PDFCreatorAndroid#10]

**Comment by tejpratap46** [comment]
It is not currently possible as it had some complications implementing it. Will sure look into possibilities of adding it again.

**Comment by tejpratap46** [comment]
From version 2.0, you have to override `getFooterView(pageIndex)` to give Footer for page

```java
@Override
protected PDFFooterView getFooterView(int pageIndex) {
    PDFFooterView footerView = new PDFFooterView(getApplicationContext());

    PDFTextView pdfTextViewPage = new PDFTextView(getApplicationContext(), PDFTextView.PDF_TEXT_SIZE.SMALL);
    pdfTextViewPage.setText(String.format(Locale.getDefault(), "Page: %d", pageIndex + 1));
    pdfTextViewPage.setLayout(new LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT,
            LinearLayout.LayoutParams.MATCH_PARENT, 0));
    pdfTextViewPage.getView().setGravity(Gravity.CENTER_HORIZONTAL);

    footerView.addView(pdfTextViewPage);

    return footerView;
}
```

**Comment by meysamhadigheh** [comment]
> From version 2.0, you have to override `getFooterView(pageIndex)` to give Footer for page
> 
> ```java
> @Override
> protected PDFFooterView getFooterView(int pageIndex) {
>     PDFFooterView footerView = new PDFFooterView(getApplicationContext());
> 
>     PDFTextView pdfTextViewPage = new PDFTextView(getApplicationContext(), PDFTextView.PDF_TEXT_SIZE.SMALL);
>     pdfTextViewPage.setText(String.format(Locale.getDefault(), "Page: %d", pageIndex + 1));
>     pdfTextViewPage.setLayout(new LinearLayout.LayoutParams(
>             LinearLayout.LayoutParams.MATCH_PARENT,
>             LinearLayout.LayoutParams.MATCH_PARENT, 0));
>     pdfTextViewPage.getView().setGravity(Gravity.CENTER_HORIZONTAL);
> 
>     footerView.addView(pdfTextViewPage);
> 
>     return footerView;
> }
> ```

Thanks a lot 🙏🏻
