### ISSUE TITLE
Custom width for a single column

### ISSUE THREAD

**Issue by rizkikurniaa** [tejpratap46/PDFCreatorAndroid#11]
How to customize the width for the columns, so that the widths of each column are not the same

**Comment by tejpratap46** [comment]
There is no straight forward way to achieve this, you can hack your way out by setting custom layout weight. But you have to intelligently set same weight to every `TextView` in same position of every row.

```java
pdfTextView.setLayout(new LinearLayout.LayoutParams(0, ViewGroup.LayoutParams.WRAP_CONTENT, 2 /* CUSTOM COLUMN WEIGHT */));
```

Insert above code after you added `Item` to `Row`. As while adding `Item` to `Row`, I reset weight to 1.
```java
tableRowView.addToRow(pdfTextView);
```

https://github.com/tejpratap46/PDFCreatorAndroid/blob/c37c74b6ac7ca0dee396b2446505fbc1b9bb22f2/app/src/main/java/com/tejpratapsingh/pdfcreatorandroid/PdfCreatorActivity.java#L141

I will look into possibilities of adding custom weight to table columns while initializing.

**Comment by tejpratap46** [comment]
Can set custom column with to Table View

```java
PDFTableView tableView = new PDFTableView(getApplicationContext(), tableHeader, tableRowView1);
// as this table has 4 columns, each will get width as per their index in array.
// Sum should be equal to 100%
int[] widthPercent = {20, 20, 20, 40};
tableView.setColumnWidth(widthPercent);
```
