### ISSUE TITLE
Print preview is set visible after pdfGenerationSuccess

### ISSUE THREAD

**Issue by Rathieshr** [tejpratap46/PDFCreatorAndroid#13]
layoutPrintPreview is set visible on pdfGenerationSuccess. makes the application show preview. According to my requirement, I should show it in my custom view. So the default preview opens and then my custom view opens up.

**Comment by tejpratap46** [comment]
You can just finish that activity in `pdfGenerationSuccess`, take handle of PDF file and do whatever you want.

Start a new `Activity` or return pdf file as `activityResult`, its your wish.

PDF cannot be generated without painting your views to the screen.
