### ISSUE TITLE
Is it possible to define page width?

### ISSUE THREAD

**Issue by victorlaerte** [tejpratap46/PDFCreatorAndroid#15]
Is it possible to define page width using `generatePDFFromWebView`?

**Comment by tejpratap46** [comment]
`generatePDFFromWebView` takes a WebView and you have to either give html Or Url. `generatePDFFromWebView` takes that webview and generates PDF with whatever is currently rendered in that webview.

You have to somehow set custom width inside that html.

**Comment by tejpratap46** [comment]
If you are facing some other issue that i didn't understand, please give a sample code of whatever you are trying to do.
