### ISSUE TITLE
Share pdf not working

### ISSUE THREAD

**Issue by ChandanNaik999** [tejpratap46/PDFCreatorAndroid#16]

**Comment by tejpratap46** [comment]
This library only concerns with creating PDF, you get access to file and you can do whatever you want with that file.

If you are facing issue while sharing a file, please Google that or Google how to share any file in Android via Intent.

Take a look here for sample:
You first have to create a provider:
https://github.com/tejpratap46/PDFCreatorAndroid/blob/0e754bd5021d5fbed1bfb57de5c9218fa425a8b4/app/src/main/AndroidManifest.xml#L37-L45

Then share it as below:
https://github.com/tejpratap46/PDFCreatorAndroid/blob/0e754bd5021d5fbed1bfb57de5c9218fa425a8b4/app/src/main/java/com/tejpratapsingh/pdfcreatorandroid/PdfViewerActivity.java#L60-L78
