### ISSUE TITLE
Using '#' in PDFUtil.generatePDFFromHTML causes everything after the # to not print

### ISSUE THREAD

**Issue by GrullonD** [tejpratap46/PDFCreatorAndroid#17]
For example:
"The cat# in the hat" will show as "The cat". Is there a work around to this? Currently can't use Unicode because of this.

**Comment by GrullonD** [comment]
For people looking. The work around is to replace "#" with "%23"

**Comment by tejpratap46** [comment]
@GrullonD have you found any reason for this or any other cases where it fails?

I will look into this anyway.

**Comment by tejpratap46** [comment]
Reason is still unknown, looks like an Android's Internal implementation issue.
Tested With other Url Encoded characters ">@#&=*+-_.,:!?()/~'%", everything looks to be fine.

For now i fixed this issue by replabce all occurances of '#' with '%23' as suggested by @GrullonD 
Thank you @GrullonD for issue.
