### ISSUE TITLE
Could not Share with other apps like GMail in Android 11

### ISSUE THREAD

**Issue by Rathieshr** [tejpratap46/PDFCreatorAndroid#18]
We could not share the pdf with other apps. As the pdf is stored in the app specific storage and Android 11 restrict this access.
https://developer.android.com/about/versions/11/privacy/storage

**Comment by tejpratap46** [comment]
Have you tested your app on android 10? Are you sure you have implemented a [FileProvider Authority](https://developer.android.com/training/secure-file-sharing/setup-sharing) in you app?
I have to tested this library in Android 11, but one of our production app is not facing any such issue.

**Comment by Rathieshr** [comment]
Yes, I have tested in Android 10 and I did not face any issue there. It occurs only in Android 11. Yes, I have implemented Fileprovider authority.

**Comment by tejpratap46** [comment]
Ok, will look into this.

**Comment by tejpratap46** [comment]
Will look into this.

**Comment by Rathieshr** [comment]
It works with File provider when using FileProvider.getUriForFile. 
Previous i used only getUriForFile directly.

**Comment by enocklubowa** [comment]
> We could not share the pdf with other apps. As the pdf is stored in the app specific storage and Android 11 restrict this access.
> https://developer.android.com/about/versions/11/privacy/storage

I also used the library on Android as well as the app on Android 11 but it couldn't attach the file.
A fix was passing the Uri to the intent instead of the absolute path.
https://github.com/tejpratap46/PDFCreatorAndroid/pull/34
