### ISSUE TITLE
Not able to add in gradle

### ISSUE THREAD

**Issue by sayanlp99** [tejpratap46/PDFCreatorAndroid#19]
![image](https://user-images.githubusercontent.com/28763093/112714926-dfa87d80-8f02-11eb-8d66-bd325ce3e589.png)

![image](https://user-images.githubusercontent.com/28763093/112714846-850f2180-8f02-11eb-9ff4-5ac1c676d106.png)

After gradle build and running the app, this error is shown

**Comment by tejpratap46** [comment]
Looks like jitpack is facing issue... i will try to fix it, but as a workaround you can clone this repo and add 'pdfcreator' as module dependency.

**Comment by tejpratap46** [comment]
Created a new release 2.1.2, check if it works.

`implementation 'com.github.tejpratap46:PDFCreatorAndroid:2.1.2'`
