### ISSUE TITLE
Don't want new activitiy

### ISSUE THREAD

**Issue by CeRBeR666** [tejpratap46/PDFCreatorAndroid#20]
Greetings,
I don't want the pdf to be opened in a new activity. It will save in the background in my current activity and I want to upload it to the server later.
How can I trigger your class in current activity?

**Comment by tejpratap46** [comment]
You can use [html-to-pdf](https://github.com/tejpratap46/PDFCreatorAndroid#html-to-pdf) option. It is not as versatile as PdfCreatorActivity.

To use PdfCreatorActivity, you have to render it on screen.
