### ISSUE TITLE
Table Column Alignment & Repeating header

### ISSUE THREAD

**Issue by madhall** [tejpratap46/PDFCreatorAndroid#21]
Hi Tej,

thank you for creating and maintaining this library.

I have been able to use and generate a pdf. It contains a table that extends to 2 or more pages. I have two issues can you please guide 

1) Since the table repeats on two or more pages - how can the table headers be repeated?
2) How to assign table column width - I have 2 columns, and I need the first to be on the left and seond on the right - justified... 

Please guide

Thanks

**Comment by tejpratap46** [comment]
1. No, Headers won't repeat per page, that is not possible with current implementation. Will look into possibilities of implementing it.
2. This is another issue and will be implemented soon (if possible), currently we give equal width to every column as each row manages their own column width and it was correct behavior in most cases, you can look into issue #11 if you want to hot-fix your pdf.

**Comment by madhall** [comment]
cool, thanks for looking into this!

**Comment by tejpratap46** [comment]
Implemented custom width, no plan to implement repeating header as it would be too complicated.

Here is an example to set custom column with to Table View:

```java
PDFTableView tableView = new PDFTableView(getApplicationContext(), tableHeader, tableRowView1);
// as this table has 4 columns, each will get width as per their index in array.
// Sum should be equal to 100%
int[] widthPercent = {20, 20, 20, 40};
tableView.setColumnWidth(widthPercent);
```

**Comment by madhall** [comment]
Thanks that is awesome! Can you please issue a release so that I can use the update? cheers

**Comment by tejpratap46** [comment]
Sure, was busy preparing docs for this library as README is going crazy.
You can use 2.2.1 version now.
