### ISSUE TITLE
Loading Images from Mobile

### ISSUE THREAD

**Issue by madhall** [tejpratap46/PDFCreatorAndroid#22]
Hi Tej, 

The user is able to upload a default image using picasso, and the uri is stored. I tried the following approach to be able to display the image from the uri for the image stored in the phone gallery but it does not work... any suggestions please?

        val imageView = PDFImageView(applicationContext)
        val imageLayoutParam = LinearLayout.LayoutParams(
            60,
            60, 0F
        )
        if(user.logoUrl != null){
            val url = URL(user.logoUrl)
            val imageBmp = BitmapFactory.decodeStream(url.openConnection().getInputStream())
            imageView.setImageScale(ImageView.ScaleType.CENTER_INSIDE)
            imageView.setImageBitmap(imageBmp)
            // imageView.setImageResource(user!!.logoUrl)
            imageLayoutParam.setMargins(0, 0, 10, 10)
            imageView.setLayout(imageLayoutParam)
            horizontalView.addView(imageView)
        }

thanks

**Comment by madhall** [comment]
this is the error i get:

Caused by: java.net.MalformedURLException: unknown protocol: content

**Comment by tejpratap46** [comment]
This issue is not related to this library, please read how to get bitmap from local file.

try this
```java
InputStream is = getContentResolver().openInputStream(uri);
Bitmap bitmap = BitmapFactory.decodeStream(is);
is.close();
```

or this:
```java
Uri mImageCaptureUri = data.getData();
Bitmap photoBmp = null;
if (mImageCaptureUri != null) {
    photoBmp = MediaStore.Images.Media.getBitmap(ac.getContentResolver(), mImageCaptureUri);
}
```
