### ISSUE TITLE
How to add footer in all pages of pdf which is generate from html 

### ISSUE THREAD

**Issue by vishalvala** [tejpratap46/PDFCreatorAndroid#28]
Hello,
 please tell me is it possible to add footer all pages of pdf which is generate from html and page of pdf is changes dynamically according to data.

**Comment by tejpratap46** [comment]
> tell me is it possible to add footer all pages of pdf which is generate from html?

Html PDF's do not have header or footer, you have to use View to PDF API's.

> page of pdf is changes dynamically according to data?

PDF will be generated using your current data. If your data changes, you have to generate pdf again using new data.

**Comment by tejpratap46** [comment]
For more information read [documentation](https://link.tejpratapsingh.com/api/link/gbpdflib)

**Comment by vishalvala** [comment]
but i want to set like when user click on logo image open link in browser this possible in pdf generated from html but in PDf api i can't set.

**Comment by tejpratap46** [comment]
I don't think that is possible with my current implementation, you cannot put link on a `PDFImageView` but you can set link on a `PDFTextView` using `HtmlCompact.fromHtml()` method.

Below is an example for `PDFTextView`:

https://github.com/tejpratap46/PDFCreatorAndroid/blob/04401cfcb77b23aeaff49e3c8ebcb94521aa254d/app/src/main/java/com/tejpratapsingh/pdfcreatorandroid/PdfCreatorActivity.java#L158-L160
