### ISSUE TITLE
how to make all borders of tableview ?

### ISSUE THREAD

**Issue by afsalkodasseri** [tejpratap46/PDFCreatorAndroid#29]
is there any option to make all borders of a tableview ?

**Comment by tejpratap46** [comment]
No, there is no straight forward styling API for tableview, but you can add
border to every textview you add into tableview.

Thanks,
Tej Pratap

**Comment by tejpratap46** [comment]
No, there is not straight forward styling API for `PDFTableView`, But you can add border to every `PDFTextView`

You can use `getView()` of `PDFTextVIew` and the add border as below:

```java
GradientDrawable gd = new GradientDrawable();
gd.setColor(0xFF00FF00); // Changes this drawbale to use a single color instead of a gradient
gd.setCornerRadius(5);
gd.setStroke(1, 0xFF000000);

pdfTextView.getView().setBackground(gd);
```
