### ISSUE TITLE
Not getting PDFPageBreakView class

### ISSUE THREAD

**Issue by AkshatDeveloper06** [tejpratap46/PDFCreatorAndroid#37]
I am not gettig the PDFPageBreakView Class. Please tell

**Comment by tejpratap46** [comment]
This is unreleased feature, will merge soon. It still has to be well tested.

**Comment by AkshatDeveloper06** [comment]
Is there any way that i can implement it because i need it for my team.

**Comment by tejpratap46** [comment]
You can clone this repo, copy `pdfcreator` module into you project, and use it that way.

**Comment by tejpratap46** [comment]
Release v3.0.2 with `PDFPageBreakView`
