### ISSUE TITLE
PDF size issue 

### ISSUE THREAD

**Issue by dhaval-devstree** [tejpratap46/PDFCreatorAndroid#38]
I am also facing the same size issue with different cases. 
1st generated PDF without adding any image -  PDF size 355 Kb.
Then again generate pdf by adding one image (122 kb - compressed image) -  PDF size 1.5 Mb
Then again generate pdf by adding same size 5 images (122 kb - compressed image) -  PDF size 8 Mb.

Please reduce the pdf size issue. When pdf contains 12-15 images that size reach at 30 Mb it's so big size for document. 

Thanks

**Comment by tejpratap46** [comment]
#35 is a different issue, it generates different sizes for same data in different devices.

I am closing this issue, will investigate this issue with issue #35.
