### ISSUE TITLE
Can't move to the next page

### ISSUE THREAD

**Issue by shreefelsayed** [tejpratap46/PDFCreatorAndroid#40]
if you can add an option to move to the next page and start generating, that would be perfect

**Comment by tejpratap46** [comment]
I did not get this, are you saying that there should be an option to let current page be empty and start adding new content to new page?

If this is the case, there is already an option called `PDFPageBreakView`, anything added after this view will be moved to new page. Read more [here](https://tejpratap46.gitbook.io/pdf-creator-android/available-views/pdfpagebreakview).

**Comment by tejpratap46** [comment]
Closing for inactive
