### ISSUE TITLE
cannot resize entire row depending on the value in textviews

### ISSUE THREAD

**Issue by turbosoft-anudeep** [tejpratap46/PDFCreatorAndroid#42]
I was trying to create a table view, but the values in each text view in the table view might vary. so need the entire row to resize depending on the value present in the text view. if you can see  the first header row I just added some characters to the first text view, the rest columns does not match the height to the first row. tried adding layout params to text view and the row. same issue persists.

![image](https://user-images.githubusercontent.com/87063547/137614369-e31b3b16-e7a1-4c9a-af57-a2f24babeb43.png)

 ```
int[] widthPercent2 = {5, 12, 17, 10, 10, 10, 10, 10, 8, 8};
    String[] headerTitle2 = {"S# fjtdhrdygkyftjf", "Item Code", "Item Name", "Cs Qty", "Pc Qty", "Cs Price", "Pc Price", "Sub Total", "VAT", "Total"};
    String[] childTitle1 = {"1", itemCode[0], itemName[0], csQty[0], pcQty[0], csPrice[0], pcPrice[0], subtotal[0], vat[0], total[0]};

 private PDFTableView.PDFTableRowView createTableHeader(String[] headerTitle) {
        PDFTableView.PDFTableRowView tableHeaderRow = new PDFTableView.PDFTableRowView(getApplicationContext());
        for (int i = 0; i < headerTitle.length; i++) {
            tableHeaderRow.addToRow(createHeaderColumn(headerTitle[i], i));
        }
        tableHeaderRow.setLayout(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT));
        return tableHeaderRow;
    }

 private PDFTextView createHeaderColumn(String title, int pos) {
        PDFTextView pdfTextView = new PDFTextView(getApplicationContext(), PDFTextView.PDF_TEXT_SIZE.P).setText(title);
        if (pos == 0) {
            pdfTextView.getView().setBackground(getResources().getDrawable(R.drawable.border_left_top_right_grey));
        } else {
            pdfTextView.getView().setBackground(getResources().getDrawable(R.drawable.border_top_right_grey));
        }


        pdfTextView.getView().setTextSize(TypedValue.COMPLEX_UNIT_SP,  (float) 3.5);
        pdfTextView.setTextTypeface(ResourcesCompat.getFont(getApplicationContext(), R.font.calibrib));
        pdfTextView.setPadding(10, 0, 0, 0);
        pdfTextView.setLayout(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT));
        return pdfTextView;
    }
```
I attach the row to the table using the below mentioned code

```
PDFTableView tableView = new PDFTableView(getApplicationContext(), createTableHeader(headerTitleInv),
                createTableChildFirstRow(childTitleInv, 1));
        tableView.setColumnWidth(widthPercentInv);
        pdfBody.addView(tableView);
        pdfBody.addView(createSeparator(Color.WHITE, 15));

```

Could anyone tell me what I'm doing wrong/missing out..

**Comment by tejpratap46** [comment]
Are you using two different set `columnWithPercentage` array?

I would suggest to modify your code by using example from [here](https://tejpratap46.gitbook.io/pdf-creator-android/available-views/pdftableview).

**Comment by turbosoft-anudeep** [comment]
> Are you using two different set `columnWithPercentage` array?
> 
> I would suggest to modify your code by using example from [here](https://tejpratap46.gitbook.io/pdf-creator-android/available-views/pdftableview).

no., I'm using same width percent array. i have developed similar to your example .

**Comment by turbosoft-anudeep** [comment]
![image](https://user-images.githubusercontent.com/87063547/137620647-c2b97183-7b9b-47ff-915f-ba29af318388.png)

Attaching another image for better understanding the issue..
i think the textviews are not resizing according to the horizontal view

**Comment by tejpratap46** [comment]
Ok, if font size or text wrapping is the issue, then this library does not handle those cases currently. You have to take care of that yourself.

I would suggest to use `setMaxLines(2)` and `setEllipsize(TextUtils.TruncateAt.END)`.

Its up-to you how much width you want to give per column, if your column is too small, text will just wrap and take up all the height it needs.
