### ISSUE TITLE
Multiple page pdf not creating as CurrentpageHeight and viewitem.getHeight is always 0 

### ISSUE THREAD

**Issue by wahdatjan** [tejpratap46/PDFCreatorAndroid#46]
Hi , Please check the below line where **_CurrentpageHeight and viewitem.getHeight is always 0_** 

https://github.com/tejpratap46/PDFCreatorAndroid/blob/ffd0c31b1b3d29a4101ff62fbed9b073f0429b8c/pdfcreator/src/main/java/com/tejpratapsingh/pdfcreator/activity/PDFCreatorActivity.java#L193

**Comment by tejpratap46** [comment]
Can you share the code snippet of your pdf.

**Comment by wahdatjan** [comment]
@tejpratap46 check this gist 
https://gist.github.com/wahdatjan/8290e4fa89d0b4e64c5c361a670fe2d3

**Comment by tejpratap46** [comment]
After looking at you implementation, you can now see why we need to render each of view before generating a pdf. Only after rendering a view we can get its height, otherwise `getHeight()` will return zero.

So you cannot generate a PDF with Views without showing it on the screen.

https://github.com/tejpratap46/PDFCreatorAndroid/blob/ffd0c31b1b3d29a4101ff62fbed9b073f0429b8c/pdfcreator/src/main/java/com/tejpratapsingh/pdfcreator/activity/PDFCreatorActivity.java#L140

That is what is happening in the above line.

**Comment by wahdatjan** [comment]
@tejpratap46  I am rendering a view before generating a pdf but only one page is getting rendered , not multiple 
Can you check this image how one page is getting cropped at the bottom https://ibb.co/tPxtbwS

**Comment by tejpratap46** [comment]
Your view might be too big. Try to create small chunks of view which are stacked one after another.

Why don't you just use the library rather than implementing everything again?

**Comment by wahdatjan** [comment]
@tejpratap46 I am using the library but getting this issue .

**Comment by tejpratap46** [comment]
But in your example, you are trying to re-implement what this library does internally.

If you want to use the library follow this guide:
https://tejpratap46.gitbook.io/pdf-creator-android/getting-started

**Comment by wahdatjan** [comment]
@tejpratap46 I am using the library but i am using using my views in the library . rest is same

**Comment by tejpratap46** [comment]
https://gist.github.com/wahdatjan/8290e4fa89d0b4e64c5c361a670fe2d3#file-pdfutility-kt-L484-L493

I cannot see a custom view in this example? Are you using a POJO to generate PDF views?

You  simply need to edit this example Activity class with your data:

https://github.com/tejpratap46/PDFCreatorAndroid/blob/ffd0c31b1b3d29a4101ff62fbed9b073f0429b8c/app/src/main/java/com/tejpratapsingh/pdfcreatorandroid/PdfCreatorExampleActivity.java#L37

Here are the steps:
1. Create a Empty Activity without any layout and extend it with `PDFCreatorActivity`. Do not set use `setContentView(int resourceId)` inside your created activity.
1. Get access to your POJO (`orderByOrderIdPojo`) in the Activity class
2. customise `getHeaderView()` with data from `orderByOrderIdPojo`
3. customise `getBodyViews()` with data from `orderByOrderIdPojo`
4. customise `getFooterView()` with data from `orderByOrderIdPojo`

Please read documentation from here https://tejpratap46.gitbook.io/pdf-creator-android/getting-started

**Comment by wahdatjan** [comment]
@tejpratap46 followed the library but page is not occupying full space .check image
<img width="828" alt="Screenshot 2022-07-21 at 2 33 57 PM" src="https://user-images.githubusercontent.com/50394351/180283845-20d2bf24-02f6-4354-9440-45c43e50336e.png">

**Comment by tejpratap46** [comment]
There must be something taking up that space.... check your footer.

**Comment by wahdatjan** [comment]
Can i use this library to print for a single  long page like a roller without a page break ?
