### ISSUE TITLE
generate pdf only after image has been retrieved from the web

### ISSUE THREAD

**Issue by madhall** [tejpratap46/PDFCreatorAndroid#51]
I am including a logo that is saved online into the pdf. By the time the image is downloaded the pdf is generated and the image is not included - any suggestions?

**Comment by tejpratap46** [comment]
You can try downloading bitmap first then set that bitmap to image view instead of using Picasso or glide.

I would suggest to prepare all assets beforehand and once you have all assets downloaded, just set them to basic views.

**Comment by tejpratap46** [comment]
Closing this now, above solution should be applied for any such case.
