### ISSUE TITLE
user restricted while installation

### ISSUE THREAD

**Issue by inshaaziz** [tejpratap46/PDFCreatorAndroid#6]
Hi
I am trying to create pdf,I dont need pdf viewer so i haven't used those activities but while installing appi am facing error 
12/31 17:10:54: Launching 'app' on Xiaomi Redmi Note 8.
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_USER_RESTRICTED

List of apks:
[0] 'D:\Pdfgenerator2\app\build\outputs\apk\debug\app-debug.apk'
Installation via USB is disabled.
Retry
Kindly hekp.

Thanks in advance!!!

**Comment by tejpratap46** [comment]
Miui phones ask if you want to install app in device(for every new app). If you tap on "No". It will silently fail and do not ask again... Pls Google this issue.

**Comment by inshaaziz** [comment]
Ok.

Thankyou
