### ISSUE TITLE
PDFUtil.generatePDFFromHTML does support <img> tag?

### ISSUE THREAD

**Issue by victorlaerte** [tejpratap46/PDFCreatorAndroid#7]
Does it support `<img>` tag using `PDFUtil.generatePDFFromHTML`? I'am trying 
`<img src="${Uri.parse("android.resource://my.package/drawable/my_image")}">` but its not working. Also tried:
`<img src="file:///android_res/drawable/my_image.png" />`

**Comment by tejpratap46** [comment]
It Does not work with URL, as webview cannot resolve those Urls, you just need to get Base64 encoded Data and set it as data source.

```java
Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.drawable.my_image);
ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
bitmap.compress(Bitmap.CompressFormat.JPEG, 100, byteStream);
byte[] byteArray = byteStream.toByteArray();
String baseString = Base64.encodeToString(byteArray,Base64.DEFAULT);
```

And then set it to img as
```html
<img src="src="data:image/png;base64, ${baseString}">
```
